<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hango.Datos\Hango.Datos.csproj" />
    <ProjectReference Include="..\Hango.Logica\Hango.Logica.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="mercadopago-sdk" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\avatares\" />
  </ItemGroup>

</Project>
